version: '3'
services:
  db:
    container_name: smarthome-db
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smarthome
    volumes:
      - ./data/db:/var/lib/postgresql/data

  redis:
    container_name: smarthome-redis
    image: redis:4.0
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data

  mongo:
    container_name: smarthome-mongo
    image: mongo:3.6
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongo:/data/db
