version: '3'
services:
  # server:
  #   container_name: smarthome-server
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db

  db:
    container_name: smarthome-db
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smarthome
    volumes:
      - ./data:/var/lib/postgresql/data
